### ISSUE TITLE
It is not possible to check types of table elements

### ISSUE THREAD

**Issue by ligurio** [fab13n/checks#3]
Imagine a Lua function `f()` that accept a table as argument:

```lua
local checks = require('checks')

local opts = {
    a = 'a',
    b = 2,
}

local function f(opts)
    checks('table')
    return
end

f(opts)
```

`checks`  checks that type of argument is a table and everything is fine.

However, it would be nice to check types of table elements too. Like this:

```lua
local checks = require('checks')

local opts = {
    a = 'a',
    b = 2,
}

local function f(opts)
    checks({
        a = 'string',
        b = 'number'
    })
    return
end

f(opts)
```

This example throw an exception:
```
sergeyb@pony:~/sources/lua-jepsen$ luajit sample2.lua 
LuajitError: sample2.lua:9: bad argument #1 to 'checks' (string expected, got table)
fatal error, exiting the event loop
```

`checks`  allows defining a checker for your custom type, like described in README for type `port`. But `table` is a common type and it is better to implement checking of types of table elements in a core functionality.

P.S. The feature described above is already implemented for [Tarantool's checks](https://github.com/tarantool/checks#table-type-qualifiers), but it is incompatible with LuaJIT (for example, it uses `startswith` unavailable in PUC Rio Lua and LuaJIT).

**Comment by fab13n** [comment]
It's possible to build a much more expressive type system indeed, it's all
a matter of design compromises. The choices behind Checks are :

   - it should be fast, people shouldn't give up on annotations in order to
   gain performances. That means simple parsing, all in C.
   - annotations' purpose is at least as much about self-documented code as
   about actual runtime enforcement. Actual runtime checks guarantee that
   the self documentation is kept in sync with the code, contrary to comments,
   though. With a single glance at the `checks(...)` one-liner on top of a
   function, you should know what is accepted by that function. You don't want
   to have to read a five-line spec.

If you have a specific table subtype that is reused regularly, you can name
it, and implement its checking function as `function checkers.<name>(x)`.
Encouraging you to give it a self-descriptive name also helps with
self-documentation.

There may be a niche for a much fancier run-time type checker, but that
would be a different project IMO.

**Comment by ligurio** [comment]
@fab13n Thanks for the detailed answer! Well, it is accepted. So I close the issue.
